name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # You can adjust this to the version of Node.js your project needs

    - name: Install dependencies
      run: npm install  # Adjust this if you're using yarn or another package manager

    - name: Build project
      run: npm run build  # Adjust this to your build command if needed

    - name: Deploy to Netlify
      run: npx netlify deploy --prod --dir=build
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}  # Use GitHub secrets to store the token
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}  # Store your Netlify site ID as a GitHub secret

